sudo: required
services:
  - docker

before_install:
  - docker build -t solymantaherian/react-test -f ./client/Dockerfile.dev ./client

scripts:
  - docker run solymantaherian/react-test npm test -- --coverage

after_success:
  - docker build -t solymantaherian/multi-client ./client
  - docker build -t solymantaherian/multi-nginx ./nginx
  - docker build -t solymantaherian/multi-server ./server
  - docker build -t solymantaherian/multi-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take these images and push to docker hub
  - docker push solymantaherian/multi-client
  - docker push solymantaherian/multi-nginx
  - docker push solymantaherian/multi-server
  - docker push solymantaherian/multi-worker


